### ISSUE TITLE
Graphics issues on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by sboehringer** [OoliteProject/oolite#497]
Oolite compiles fine on openSUSE Tumbleweed (VERSION_ID="20241215"). However, neither text is not diplayed properly nor do many object seem to be rendered properly.

Some information on the system:
```
inxi -G
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Lucienne driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.14 with: Xwayland v: 24.1.4 driver: X:
    loaded: modesetting unloaded: vesa dri: radeonsi gpu: amdgpu resolution:
    1: 1920x1200~60Hz 2: 1080x1920~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.3.1 renderer: AMD
    Radeon Graphics (radeonsi renoir LLVM 19.1.5 DRM 3.59 6.11.8-1-default)
  API: Vulkan v: 1.3.296 drivers: N/A surfaces: xcb,xlib
```
![Screenshot_oolite](https://github.com/user-attachments/assets/888ede2e-0647-45c6-adf2-a4d43e8d7901)
